---
# deploy stage
- name: deploy coolstore in {{ project_stage }}
  shell: "{{ openshift_cli }} process -f {{ deployments_template }} --param=APP_VERSION=test --param=HOSTNAME_SUFFIX={{ project_stage }}.{{ hostname_suffix }} -n {{ project_stage }} | {{ openshift_cli }} create -f - -n {{ project_stage }}"
  ignore_errors: true

- name: prune deployments in {{ project_stage }}
  shell: "{{ openshift_cli }} delete dc,svc,route,pvc,cm -l {{ prune_deployments_selector_stage }} -n {{ project_stage }}"
  ignore_errors: true
  when:
  - prune_deployments_selector_stage is defined
  - prune_deployments_selector_stage is not none
  - prune_deployments_selector_stage|trim() != ""

# remove persistent storage
- import_tasks: make_ephemeral.yml
  vars:
    project_name: "{{ project_stage }}"
  when: ephemeral