---
# github 
github_account: jbossdemocentral
github_ref: master

# templates
builds_template: https://raw.githubusercontent.com/{{ github_account }}/coolstore-microservice/{{ github_ref }}/openshift/templates/coolstore-builds-template.yaml
coolstore_github_repo: https://github.com/{{github_account}}/coolstore-microservice.git
deployments_template: https://raw.githubusercontent.com/{{ github_account }}/coolstore-microservice/{{ github_ref }}/openshift/templates/coolstore-deployments-template.yaml
netflix_oss_template: https://raw.githubusercontent.com/{{ github_account }}/coolstore-microservice/{{ github_ref }}/openshift/templates/netflix-oss-list.yaml
bluegreen_deployment_template: https://raw.githubusercontent.com/{{ github_account }}/coolstore-microservice/{{ github_ref }}/openshift/templates/inventory-bluegreen-template.yaml
pipeline_template: https://raw.githubusercontent.com/{{ github_account }}/coolstore-microservice/{{ github_ref }}/openshift/templates/inventory-pipeline-template.yaml
simple_pipeline_template: https://raw.githubusercontent.com/{{ github_account }}/coolstore-microservice/{{ github_ref }}/openshift/templates/inventory-pipeline-template-simple.yaml
inventory_template: https://raw.githubusercontent.com/{{ github_account }}/coolstore-microservice/{{ github_ref }}/openshift/templates/inventory-template.json

# project names
project_cicd: cicd

project_prod: coolstore-prod
project_prod_name: "CoolStore PROD"
project_prod_desc: "CoolStore PROD Environment"

project_stage: coolstore-test
project_stage_name: "CoolStore TEST"
project_stage_desc: "CoolStore Test Environment"

project_test: inventory-test
project_test_name: "Inventory DEV"
project_test_desc: "Inventory DEV Environment"

project_dev: developer
project_dev_name: "Developer Project"
project_dev_desc: "Personal Developer Project"

project_default: coolstore
project_default_name: "CoolStore MSA"
project_default_desc: "CoolStore MSA"

# project configs
project_annotations: demo=demo-modern-arch
project_join_with: cicd
disable_stage_project: false

# openshift
openshift_cli: oc
openshift_master: 127.0.0.1.nip.io:8443
hostname_suffix: apps.127.0.0.1.nip.io
prebuilt_images_project_name: coolstore-image-builds

# gogs
gogs_hostname: gogs-gogs.127.0.0.1.nip.io
gogs_admin_user: gogs
gogs_admin_password: gogs
gogs_user: developer
gogs_password: developer

# misc
maven_mirror_url: 
keep_build_configs: true
bluegreen_image: inventory
prune_deployments_selector: 
prune_deployments_selector_prod: "{{ prune_deployments_selector }}"
prune_deployments_selector_stage: "{{ prune_deployments_selector }}"
prune_builds_selector: 
enable_cicd: true